apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "authn.fullname" . }}
  labels:
    {{- include "authn.labels" . | nindent 4 }}
rules:
# allow creating, deleting and retrieving any CertificateSigningRequest
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - get
  - create
  - list
  - delete
  - watch
  - approve
  - update
# allow approving a CertificateSigningRequest:
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/approval
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "authn.fullname" . }}-group
  labels:
    {{- include "authn.labels" . | nindent 4 }}
rules:
- apiGroups:
  - templates.krateo.io
  resources:
  - restactions
  verbs:
  - get