apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "authn.fullname" . }}-{{ .Release.Namespace }}
  labels:
    {{- include "authn.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "authn.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "authn.fullname" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "authn.fullname" . }}-group-{{ .Release.Namespace }}
subjects:
- kind: Group
  name: authn
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: {{ include "authn.fullname" . }}-group-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io