apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "authn.fullname" . }}
  labels:
    {{- include "authn.labels" . | nindent 4 }}
data:
  AUTHN_PORT: "{{ .Values.service.port }}"
  AUTHN_NAMESPACE: {{ .Release.Namespace }}
  POD_NAMESPACE: {{ .Release.Namespace }}
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}